### ISSUE TITLE
Problem z narzędziem Docker

### ISSUE THREAD

**Issue by Pi0ter** [p00rCoderZ/web#2]
Szczęść Boże,

Wystąpił problem z narzędziem Docker.
Proszę o instrukcję krok po kroku jak się z tego korzysta.

Pozdrawiam,
Piotr Kłak

**Comment by resont** [comment]
![9d5](https://user-images.githubusercontent.com/50152012/70854583-008bc180-1ebe-11ea-9ad0-2625de823f71.png)

**Comment by szykol** [comment]
Szczesc Boze. Z jakimi problemami pan się zmaga? Z jakiego systemu pan korzysta? 
@Pi0ter

**Comment by Pi0ter** [comment]
Pochwalony, @szykol 
Z jedynego słusznego:  Windows 10 x64 , zasilacz nie figuruje na czarnej liście aczkolwiek problemy nadal występują.

Wątpliwości dotyczą obsługi tego ustrojstwa, postępy zostały uczynione w kierunku instalacji i postawienia pierwszego kontenera z wątpliwym wykorzystaniem repozytoriów. Dalsze działania wymagane do osiągnięcia sukcesu nadal pozostają okryte mgłą tajemnicy, a na horyzoncie nie widać ratunku, więc pozostaje tylko wołanie o pomoc puszczone w eter oraz wiadomości w butelce wyrzucona za burtę tego ledwo co dryfującego okrętu...

**Comment by szykol** [comment]
Po zainstalowaniu docker desktop dla windowsa zalecam udostepnienie aplikacji dysku na ktorym figuruje obraz kontenera. Zalecam rowniez od tego momentu korzystanie z konsoli i komend.

Proszę pobrać któreś z repozytorium z naszej organizacji, wejsc w pobrany folder i podążac za instrukcjami napisanymi w pliku README.md. Pozdrawiam

**Comment by resont** [comment]
Szczęść Boże,

Temat zaniża poziom gita. Proszę na przyszłość używać narzędzia wyszukaj.
Temat zamykam.
