### ISSUE TITLE
Zmień logo

### ISSUE THREAD

**Issue by Pi0ter** [p00rCoderZ/web#45]
Zmień logo
![Logo Kurier UP2](https://user-images.githubusercontent.com/48968610/72671930-5cfc7680-3a52-11ea-82a6-d4d618d4e86c.png)

**Comment by szykol** [comment]
@Pi0ter Moze byc takie ?

**Comment by Pi0ter** [comment]
>  Kręciła przecząco głową. Oczywiście, że pamiętała, ale pamięć była jej przekleństwem. Nie chciała pamiętać. Przeszłość była zła. Zło weszło do jej ciała razem z wszczepianymi bakteriami, nieszczęsnymi płodami, wreszcie z ruskim nasieniem i zabrało ze sobą wszystko co dobre.
> 
> Ałbena Grabowska - Stulecie Winnych. Ci, którzy walczyli

**Comment by Pi0ter** [comment]
@szykol

**Comment by szykol** [comment]
> Skoro można pomyśleć,
że może być lepiej,
to znaczy, że 
już jest lepiej
>
>Olga Tokarczuk,
>"Moment niedźwiedzia"

**Comment by Pi0ter** [comment]
> Pierdolę to wszystko" - mówiła często Lena, lecz niczego nie pierdoliła i wszystkim się przejmowała.
> 
> Waldemar Borzestowski - Bulterier Samson i ja

**Comment by Pi0ter** [comment]
> "Pierdolę to wszystko" - mówiła często Lena, lecz niczego nie pierdoliła i wszystkim się przejmowała.
> 
> Waldemar Borzestowski - Bulterier Samson i ja

**Comment by Pi0ter** [comment]
@szykol

**Comment by Pi0ter** [comment]
![logoCompact](https://user-images.githubusercontent.com/48968610/72687696-cc30a400-3b00-11ea-9640-a8c9279d43c2.png)

**Comment by Pi0ter** [comment]
![logoCompact2](https://user-images.githubusercontent.com/48968610/72688244-84604b80-3b05-11ea-9a9c-0973bfd5fb3e.png)

**Comment by Pi0ter** [comment]
@szykol

**Comment by szykol** [comment]
@Pi0ter loga zmienione
~temat wałkowany wielokrotnie, następnym razem użyj funkcji szukaj~
